services:
# ------------------------- FastAPI-----------------------------------------------
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000" # Port exposed
    env_file:
      - .env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
# ------------------------- Gradio UI---------------------------------------------
  gradio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradio_ui
    command: python gradio_ui.py
    ports:
      - "7860:7860" # Port exposed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - fastapi
# # ------------------------- Jupyter Notebook--------------------------------------
#   jupyter:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: jupyter_dev
#     command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
#     ports:
#       - "8888:8888" # Port exposed
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://0.0.0.0:8888"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
# ------------------------- Tests-------------------------------------------------
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_runner
    env_file:
      - .env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    command: sh -c "python tests/unittests.py ; pytest tests/integration_tests.py"
    depends_on:
      - fastapi
# ----------------- Supabase----------------------------------------------
# This is to create a local database but since we are using a cloud db, there's no need for local.
#   supabase:
#     image: postgres:15
#     container_name: supabase_db
#     ports:
#       - "54321:5432" # Port exposed
#     env_file:
#       - .env
#     environment:
#       - SUPABASE_URL=${SUPABASE_URL}
#       - SUPABASE_KEY=${SUPABASE_KEY}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_HOST=${POSTGRES_HOST}

#     volumes:
#       - supabase_data:/var/lib/postgresql/data      # This is postgres default data directory
#     healthcheck:
#       test: ["CMD", "pg_isready", "-U", "postgres"] # Postgres integrated test to check if supabase is receiving and connecting to requests appropriately
#       interval: 30s
#       timeout: 10s
#       retries: 3

# volumes:
#   supabase_data:
