version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: falsebait
    ports:
      - "8000:8000"   # for FastAPI
      - "8888:8888"   # for jupyter
      - "7860:7860"   # for gradio
    volumes:
      - .:/falsebait
    restart: unless-stopped
